/** Curated Font Awesome icons for admin pickers (solid + brands). */
export const FA_ICON_OPTIONS: { id: string; label: string; class: string; group: string }[] = [
  { id: "shield", label: "Shield", class: "fa-solid fa-shield-halved", group: "Club" },
  { id: "futbol", label: "Football", class: "fa-solid fa-futbol", group: "Club" },
  { id: "trophy", label: "Trophy", class: "fa-solid fa-trophy", group: "Club" },
  { id: "star", label: "Star", class: "fa-solid fa-star", group: "Club" },
  { id: "crown", label: "Crown", class: "fa-solid fa-crown", group: "Club" },
  { id: "medal", label: "Medal", class: "fa-solid fa-medal", group: "Club" },
  { id: "flag", label: "Flag", class: "fa-solid fa-flag", group: "Club" },
  { id: "fire", label: "Fire", class: "fa-solid fa-fire-flame-curved", group: "Club" },
  { id: "ticket", label: "Ticket", class: "fa-solid fa-ticket", group: "Events" },
  { id: "calendar", label: "Calendar", class: "fa-solid fa-calendar-days", group: "Events" },
  { id: "calendar-check", label: "Calendar Check", class: "fa-solid fa-calendar-check", group: "Events" },
  { id: "calendar-plus", label: "Calendar Plus", class: "fa-solid fa-calendar-plus", group: "Events" },
  { id: "tv", label: "TV / Watch", class: "fa-solid fa-tv", group: "Events" },
  { id: "microphone", label: "Microphone", class: "fa-solid fa-microphone", group: "Events" },
  { id: "map-pin", label: "Map Pin", class: "fa-solid fa-map-pin", group: "Events" },
  { id: "users", label: "Users", class: "fa-solid fa-users", group: "People" },
  { id: "user", label: "User", class: "fa-solid fa-user", group: "People" },
  { id: "user-plus", label: "User Plus", class: "fa-solid fa-user-plus", group: "People" },
  { id: "user-check", label: "User Check", class: "fa-solid fa-user-check", group: "People" },
  { id: "user-xmark", label: "User Remove", class: "fa-solid fa-user-xmark", group: "People" },
  { id: "people-group", label: "Group", class: "fa-solid fa-people-group", group: "People" },
  { id: "people-roof", label: "Family", class: "fa-solid fa-people-roof", group: "People" },
  { id: "child", label: "Child", class: "fa-solid fa-child", group: "People" },
  { id: "envelope", label: "Envelope", class: "fa-solid fa-envelope", group: "Contact" },
  { id: "phone", label: "Phone", class: "fa-solid fa-phone", group: "Contact" },
  { id: "mobile", label: "Mobile", class: "fa-solid fa-mobile-screen-button", group: "Contact" },
  { id: "location", label: "Location", class: "fa-solid fa-location-dot", group: "Contact" },
  { id: "comment", label: "Comment", class: "fa-solid fa-comment", group: "Contact" },
  { id: "comments", label: "Comments", class: "fa-solid fa-comments", group: "Contact" },
  { id: "bag", label: "Shopping", class: "fa-solid fa-bag-shopping", group: "Shop" },
  { id: "cart", label: "Cart", class: "fa-solid fa-cart-shopping", group: "Shop" },
  { id: "store", label: "Store", class: "fa-solid fa-store", group: "Shop" },
  { id: "shirt", label: "Shirt", class: "fa-solid fa-shirt", group: "Shop" },
  { id: "tags", label: "Tags", class: "fa-solid fa-tags", group: "Shop" },
  { id: "newspaper", label: "News", class: "fa-solid fa-newspaper", group: "Content" },
  { id: "images", label: "Gallery", class: "fa-solid fa-images", group: "Content" },
  { id: "camera", label: "Camera", class: "fa-solid fa-camera", group: "Content" },
  { id: "video", label: "Video", class: "fa-solid fa-video", group: "Content" },
  { id: "book", label: "Book", class: "fa-solid fa-book-open", group: "Content" },
  { id: "folder", label: "Folder", class: "fa-solid fa-folder-open", group: "Content" },
  { id: "file", label: "File", class: "fa-solid fa-file-lines", group: "Content" },
  { id: "handshake", label: "Partners", class: "fa-solid fa-handshake", group: "Content" },
  { id: "bullseye", label: "Target", class: "fa-solid fa-bullseye", group: "Content" },
  { id: "heart", label: "Heart", class: "fa-solid fa-heart", group: "Actions" },
  { id: "bolt", label: "Bolt", class: "fa-solid fa-bolt", group: "Actions" },
  { id: "gift", label: "Gift", class: "fa-solid fa-gift", group: "Actions" },
  { id: "bell", label: "Bell", class: "fa-solid fa-bell", group: "Actions" },
  { id: "inbox", label: "Inbox", class: "fa-solid fa-inbox", group: "Actions" },
  { id: "gear", label: "Settings", class: "fa-solid fa-gear", group: "Actions" },
  { id: "sliders", label: "Sliders", class: "fa-solid fa-sliders", group: "Actions" },
  { id: "lock", label: "Lock", class: "fa-solid fa-lock", group: "Actions" },
  { id: "unlock", label: "Unlock", class: "fa-solid fa-unlock", group: "Actions" },
  { id: "key", label: "Key", class: "fa-solid fa-key", group: "Actions" },
  { id: "chart", label: "Chart", class: "fa-solid fa-chart-line", group: "Actions" },
  { id: "chart-bar", label: "Bar Chart", class: "fa-solid fa-chart-bar", group: "Actions" },
  { id: "gauge", label: "Dashboard", class: "fa-solid fa-gauge", group: "Actions" },
  { id: "house", label: "Home", class: "fa-solid fa-house", group: "Actions" },
  { id: "link", label: "Link", class: "fa-solid fa-link", group: "Actions" },
  { id: "share", label: "Share", class: "fa-solid fa-share-nodes", group: "Actions" },
  { id: "download", label: "Download", class: "fa-solid fa-download", group: "Actions" },
  { id: "upload", label: "Upload", class: "fa-solid fa-upload", group: "Actions" },
  { id: "print", label: "Print", class: "fa-solid fa-print", group: "Actions" },
  { id: "magnifying-glass", label: "Search", class: "fa-solid fa-magnifying-glass", group: "Actions" },
  { id: "filter", label: "Filter", class: "fa-solid fa-filter", group: "Actions" },
  { id: "id-card", label: "ID Card", class: "fa-solid fa-id-card", group: "Membership" },
  { id: "address-card", label: "Member Card", class: "fa-solid fa-address-card", group: "Membership" },
  { id: "credit-card", label: "Payment", class: "fa-solid fa-credit-card", group: "Membership" },
  { id: "money-bill", label: "Money", class: "fa-solid fa-money-bill-wave", group: "Membership" },
  { id: "circle-check", label: "Check", class: "fa-solid fa-circle-check", group: "Status" },
  { id: "circle-xmark", label: "X Mark", class: "fa-solid fa-circle-xmark", group: "Status" },
  { id: "clock", label: "Clock", class: "fa-solid fa-clock", group: "Status" },
  { id: "hourglass", label: "Hourglass", class: "fa-solid fa-hourglass-half", group: "Status" },
  { id: "triangle-exclamation", label: "Warning", class: "fa-solid fa-triangle-exclamation", group: "Status" },
  { id: "circle-info", label: "Info", class: "fa-solid fa-circle-info", group: "Status" },
  { id: "arrow-right", label: "Arrow Right", class: "fa-solid fa-arrow-right", group: "Arrows" },
  { id: "arrow-left", label: "Arrow Left", class: "fa-solid fa-arrow-left", group: "Arrows" },
  { id: "chevron-right", label: "Chevron Right", class: "fa-solid fa-chevron-right", group: "Arrows" },
  { id: "chevron-down", label: "Chevron Down", class: "fa-solid fa-chevron-down", group: "Arrows" },
  { id: "angles-right", label: "Angles Right", class: "fa-solid fa-angles-right", group: "Arrows" },
  { id: "building", label: "Building", class: "fa-solid fa-building", group: "Places" },
  { id: "school", label: "School", class: "fa-solid fa-school", group: "Places" },
  { id: "church", label: "Church", class: "fa-solid fa-church", group: "Places" },
  { id: "globe", label: "Globe", class: "fa-solid fa-globe", group: "Places" },
  { id: "facebook", label: "Facebook", class: "fa-brands fa-facebook-f", group: "Social" },
  { id: "instagram", label: "Instagram", class: "fa-brands fa-instagram", group: "Social" },
  { id: "x-twitter", label: "X / Twitter", class: "fa-brands fa-x-twitter", group: "Social" },
  { id: "youtube", label: "YouTube", class: "fa-brands fa-youtube", group: "Social" },
  { id: "whatsapp", label: "WhatsApp", class: "fa-brands fa-whatsapp", group: "Social" },
  { id: "tiktok", label: "TikTok", class: "fa-brands fa-tiktok", group: "Social" },
  { id: "linkedin", label: "LinkedIn", class: "fa-brands fa-linkedin-in", group: "Social" },
  { id: "google", label: "Google", class: "fa-brands fa-google", group: "Social" },
  { id: "telegram", label: "Telegram", class: "fa-brands fa-telegram", group: "Social" },
  { id: "snapchat", label: "Snapchat", class: "fa-brands fa-snapchat", group: "Social" },
  { id: "discord", label: "Discord", class: "fa-brands fa-discord", group: "Social" },
  { id: "spotify", label: "Spotify", class: "fa-brands fa-spotify", group: "Social" },
  { id: "apple", label: "Apple", class: "fa-brands fa-apple", group: "Social" },
  { id: "android", label: "Android", class: "fa-brands fa-android", group: "Social" },
];
